run:
  skip-dirs-use-default: false

linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - gosec
    - unconvert
    - gocognit
    - gocyclo
  fast: true

linters-settings:
  misspell:
    locale: US
  govet:
    check-shadowing: false
  goimports:
    local-prefixes: github.com/sv-tools/bumptag
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
